version: '3.8'

services:
  db-consultas:
    image: mysql:8.0
    container_name: db_prontoconsulta_consultas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_prontoconsulta_consultas
      MYSQL_USER: consultas_user
      MYSQL_PASSWORD: consultas_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_consultas:/var/lib/mysql

volumes:
  mysql_data_consultas:
    driver: local
